# Generated by Django 4.2.27 on 2026-02-04 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deadline',
        ),
    ]
