# Generated by Django 4.2.27 on 2026-02-15 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_alter_course_options_course_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('WEB', 'Web Development'), ('DS', 'Data Structures'), ('ML', 'Machine Learning'), ('DESIGN', 'Design'), ('GENERAL', 'General')], default='GENERAL', max_length=30),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL),
        ),
    ]
