# Generated by Django 4.2.27 on 2026-02-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
