# Generated by Django 4.2.27 on 2026-02-04 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deadline',
            name='created_by',
        ),
    ]
