# Generated by Django 4.2.27 on 2026-02-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_deadline_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='type',
            field=models.CharField(choices=[('ASSIGNMENT', 'Assignment'), ('QUIZ', 'Quiz'), ('EXAM', 'Exam')], default='ASSIGNMENT', max_length=20),
        ),
    ]
