# Generated by Django 4.2.27 on 2026-02-04 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_deadline_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deadline',
            name='type',
        ),
    ]
