# Generated by Django 4.2.27 on 2026-02-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_enrollment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
