# Generated by Django 4.2.27 on 2026-03-01 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusupdate',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='statusupdate',
            name='is_pinned',
        ),
        migrations.RemoveField(
            model_name='statusupdate',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='statusupdate',
            name='parent',
        ),
        migrations.AddField(
            model_name='statusupdate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='statusupdate',
            name='content',
            field=models.TextField(max_length=1000),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='status.statusupdate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_comments', to=settings.AUTH_USER_MODEL)),
                ('status_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='status.statusupdate')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('status_update', 'user'), name='unique_status_like'),
        ),
    ]
