# Generated by Django 4.2.27 on 2026-02-28 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusupdate',
            options={'ordering': ['-is_pinned', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='statusupdate',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='statusupdate',
            name='likes',
        ),
        migrations.AddField(
            model_name='statusupdate',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='statusupdate',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statusupdate',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='status.statusupdate'),
        ),
        migrations.AlterField(
            model_name='statusupdate',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to=settings.AUTH_USER_MODEL),
        ),
    ]
